### PR TITLE
[tsv-files][xs]: updated parserDatabase by adding tsv format with csv…

### PR DESCRIPTION
**Pull request by Mikanebu**
* added `tsv` format into `parserDatabase`

### CODE REVIEW

**Review by anuveyatsu — COMMENTED** [review]
Great, let's add a test for it (note that we have submoduled "test-data" repo in the "fixtures")

**Comment by Mikanebu** [comment]
@anuveyatsu That's why I texted you that tests will be in `data-cli` repo

**Comment by Mikanebu** [comment]
@anuveyatsu Tests, please review https://github.com/datahq/data-cli/pull/293

**Review by anuveyatsu — APPROVED** [review]
Great, merging

**Pull request merged**
