### PR TITLE
Fixes /#99 Do not include build files in the project

### LINKED ISSUE #99: Do not include build files in the project
## Acceptance criteria 
- [x] Build files should not be included in the project.
- [x] The content `datajs` folder is moved outside
- [x] Move the FileInterface class outside File script. 
- [x] When I run `yarn build:browser` it builds the files in _dist/browser_ folder
- [x] When I run `yarn build:node` it builds the files in _dist/node_ folder
- [x] The main in the package.json is mount to "dist/node/index.js"
- [x] README is updated accordingly

### PR DESCRIPTION
**Pull request by risenW**
Related Issue #99 

## Task
- [x] Build files should not be included in the project.
- [x] The content `datajs` folder is moved outside
- [x] Move the FileInterface class outside File script. 
- [x] When I run `yarn build:browser` it builds the files in _dist/browser_ folder
- [x] When I run `yarn build:node` it builds the files in _dist/node_ folder
- [x] The main in the package.json is mount to "dist/node/index.js"
- [x] README is updated accordingly

### CODE REVIEW

**Comment by kmanaseryan** [comment]
@risenW we shouldn't merge this before #98  . Since you have merged that branch into this. So will review later

**Comment by risenW** [comment]
> @risenW we shouldn't merge this before #98 . Since you have merged that branch into this. So will review later

Okay

**Comment by kmanaseryan** [comment]
~@mariorodeghiero~ @risenW  can you resolve conflicts?

**Review by kmanaseryan — APPROVED** [review]
LGTM

**Pull request merged**
